image: codefresh/webhook-plugin
tag: "master"
version: "0.1.0"
description: Plugin which simply send notification
keywords:
  - webhook
categories:
  - notification
sources:
  - https://github.com/codefresh-io/webhook-plugin
maintainers:
  - name: Andrii Shaforostov
email: andrii@codefresh.io
envs:
  - name: WEBHOOK_USERNAME
    type: required
    description: User name
  - name: WEBHOOK_PASSWORD
    type: required
    description: User password
  - name: WEBHOOK_TOKEN
    type: required
    description: token for authorization
  - name: WEBHOOK_BODY
    type: required
    description: body of http request
